name: 'GitHub Demo Deployments - review'
description: Reviews the existing demo deployments and updates them based on findings
author: 'Peter Murray'

inputs:
  github_token:
    description: The GitHub token to use
    default: ${{ github.token }}

  warn_active_days:
    description: The number of days before a warning is to be registered
    default: 7

  terminate_active_days:
    description: The number of active days before the repository will be terminated
    default: 15

outputs:
  deployments_to_warn_json:
    description: The deployments to warn on

  deployments_to_warn_count:
    description: The number of deployments to warn on

  deployments_to_terminate_json:
    description: The deployments to terminate

  deployments_to_terminate_count:
    description: The number of deployments to terminate

runs:
  using: node16
  main: '../dist/review-demo-deployments/index.js'